version: '3.8'

services:
  app1:
    build:
      context: ./products-api
    ports:
      - "8080:8080"
    container_name: products-api
    networks:
      - minha_rede

  app2:
    build:
      context: ./customers-api
    ports:
      - "8081:8080"
    container_name: customers-api
    networks:
      - minha_rede

  app3:
    build:
      context: ./orders-api
    ports:
      - "8082:8080"
    container_name: orders-api
    networks:
      - minha_rede

networks:
  minha_rede:
    driver: bridge