version: '3.8'

services:
  app1:
    build:
      context: ./products
    ports:
      - "8080:8080"
    container_name: api-products
    networks:
      - minha_rede

  app2:
    build:
      context: ./customers-api
    ports:
      - "8081:8080"
    container_name: api-customers
    networks:
      - minha_rede

networks:
  minha_rede:
    driver: bridge