services:
  postgres:
    extends:
      file: logistics-api/docker-compose.yml
      service: postgres

  zookeeper:
    extends:
      file: logistics-api/docker-compose.yml
      service: zookeeper

  kafka:
    extends:
      file: logistics-api/docker-compose.yml
      service: kafka

  products-management:
    container_name: products-api
    build:
      context: ./products-api
    networks:
      - minha_rede

  customers-management:
    container_name: customers-api
    build:
      context: ./customers-api
    networks:
      - minha_rede

#  orders-management:
#    container_name: orders-api
#    build:
#      context: ./orders-api
#    networks:
#      - minha_rede

  logistics-management:
    container_name: logistics-api
    build:
      context: ./logistics-api
    networks:
      - minha_rede
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - products-management
      - customers-management
#      - orders-management
      - logistics-management
    networks:
      - minha_rede

networks:
  minha_rede:
    driver: bridge
  logistics_kafka-network:
    driver: bridge

volumes:
  postgres_data: